config_cls_name: kd_runner

data:
    data_name: query_intention
    train_dir: 'data/train'
    valid_dir: 'data/valid'
    test_dir: 'data/test'

    input_keys: ['query', 'context']
    output_keys: ['intention', 'main_category', 'color', 'gender']
    rationale_key: 'reasoning'
    
model:
    model_name: 'flan-t5'
    model_dir: 'models/flan-t5'

generation:
  temperature: 0.3
    top_p: 0.9
    repetition_penalty: 1.1
    
training:
    max_epochs: 10
    learning_rate: 1e-4