config_cls_name: kd_trainer_config

data:
    data_name: query_intention
    train_dir: query_train.json
    valid_dir: query_valid.json
    test_dir: query_test.json

    input_keys: ['query', 'context']
    output_keys: ['intention', 'main_category', 'color', 'gender']
    rationale_key: 'reasoning'

model:
    model_name: 'flan-t5'
    model_dir: '/workspaces/data/cache/huggingface/hub/models--google--flan-t5-large'

generation:
    temperature: 0.3
    top_p: 0.9
    repetition_penalty: 1.1

training:
    learning_rate: 1e-4
    output_dir: './outputs'